/* jshint esversion: 11, browser: true, laxbreak: true */
/* exported PLACE_DETAILS */
const PLACE_DETAILS = {
  osaka: {
    tag: "먹고, 걷고, 즐기는 도시",
    heroDesc: "활기찬 거리와 다양한 먹거리가 많은 도시입니다. 처음 일본 여행에도 부담 없이 즐기기 좋습니다.",
    intro: "오사카는 먹거리와 볼거리가 가까운 곳에 모여 있어 처음 방문하는 분들도 금방 익숙해지는 도시입니다. 낮에는 쇼핑과 관광, 저녁에는 거리 음식과 야경을 즐기기 좋습니다.",
    season: "3월 ~ 5월, 10월",
    cost: "약 80만원~",
    days: "3박 4일",
    flight: "약 2시간",
    spots: [
      { name: "도톤보리", desc: "네온사인과 길거리 음식으로 유명한 번화가", img: "images/spots/osaka/dotonbori.jpg", best: true },
      { name: "오사카성", desc: "오사카를 대표하는 역사적인 성", img: "images/spots/osaka/osaka_castle.jpg" },
      { name: "신세카이", desc: "레트로 분위기의 거리와 타워 전망", img: "images/spots/osaka/shinsekai.jpg" },
      { name: "유니버셜 스튜디오 재팬", desc: "테마파크에서 하루를 보내기 좋은 곳", img: "images/spots/osaka/universal_studio_japan.jpg" },
    ],
    enjoy: [
      { name: "길거리 음식", desc: "타코야키와 오코노미야키를 먹어보기", img: "images/spots/osaka/food.jpg" },
      { name: "성 주변 산책", desc: "오사카성 공원을 천천히 걸어보기", img: "images/spots/osaka/park.jpg" },
      { name: "쇼핑", desc: "신사이바시와 난바에서 쇼핑하기", img: "images/spots/osaka/shopping.jpg" },
      { name: "야경 보기", desc: "도톤보리 강변의 밤 풍경 감상하기", img: "images/spots/osaka/night.jpg" },
    ],
    tips: [
      { title: "저녁에 도톤보리 방문", text: "불이 켜진 거리가 야경이 예뻐요." },
      { title: "교통패스 확인", text: "1일권이 있으면 이동비를 아낄 수 있어요." },
      { title: "현금 준비", text: "작은 가게는 현금만 받는 경우가 있어요." },
      { title: "줄 서기 각오", text: "인기 맛집은 웨이팅이 있을 수 있어요." },
    ],
  },
  tokyo: {
    tag: "전통과 현대가 공존하는 도시",
    heroDesc: "쇼핑, 미식, 관광을 한곳에서 즐길 수 있는 일본의 대표 도시입니다.",
    intro: "도쿄는 전통 사찰부터 최신 쇼핑 거리까지 다양한 매력이 있는 도시입니다. 첫 방문이라면 시부야, 아사쿠사, 시나가와 등 동선을 나눠서 둘러보는 것이 좋습니다.",
    season: "3월 ~ 5월, 10월 ~ 11월",
    cost: "약 100만원~",
    days: "4박 5일",
    flight: "약 2시간 30분",
    spots: [
      { name: "센소지", desc: "도쿄에서 가장 오래된 사찰", img: "images/spots/tokyo/sensoji_temple.jpg", best: true },
      { name: "시부야", desc: "교차로와 쇼핑, 젊은 문화의 중심", img: "images/spots/tokyo/shibuya.jpg" },
      { name: "도쿄 타워", desc: "도쿄 야경을 한눈에 볼 수 있는 랜드마크", img: "images/spots/tokyo/tokyo_tower.jpg" },
      { name: "우에노 공원", desc: "박물관과 벚꽃, 산책하기 좋은 공원", img: "images/spots/tokyo/ueno_park.jpg" },
    ],
    enjoy: [
      { name: "전통 거리 산책", desc: "아사쿠사 나카미세 거리 걷기", img: "images/spots/tokyo/street.jpg" },
      { name: "쇼핑", desc: "시부야, 하라주쿠, 긴자 쇼핑 즐기기", img: "images/spots/tokyo/shopping.jpg" },
      { name: "스시 맛보기", desc: "현지 스시와 라멘 맛집 탐방하기", img: "images/spots/tokyo/sushi.jpg" },
      { name: "야경 보기", desc: "도쿄 타워나 스카이트리 전망 감상하기", img: "images/spots/tokyo/skytree.jpg" },
    ],
    tips: [
      { title: "교통카드 충전", text: "Suica나 Pasmo를 미리 준비하면 이동이 편해요." },
      { title: "이른 아침 명소 방문", text: "인기 장소는 오전이 덜 붐벼요." },
      { title: "동선 나누기", text: "하루에 너무 많은 곳을 계획에 넣지 마세요." },
      { title: "편한 신발", text: "도보 이동이 많으니 편한 신발이 중요해요." },
    ],
  },
  jeju: {
    tag: "바다와 오름, 드라이브를 즐길 수 있는 섬",
    heroDesc: "국내 대표 휴양지로 가족, 연인, 혼자 여행하기에도 좋은 섬입니다.",
    intro: "제주는 바다, 오름, 카페, 드라이브 코스가 잘 갖춰진 섬입니다. 렌트카로 이동하면 더 자유롭게 일정을 짤 수 있고, 날씨에 따라 동쪽·서쪽 코스를 나누면 좋습니다.",
    season: "4월 ~ 6월, 9월 ~ 10월",
    cost: "약 50만원~",
    days: "3박 4일",
    flight: "약 1시간 10분",
    spots: [
      { name: "성산일출봉", desc: "제주를 대표하는 자연 명소", img: "images/spots/jeju/seongsan_ilchulbong.jpg", best: true },
      { name: "한라산", desc: "등산과 자연을 즐길 수 있는 곳", img: "images/spots/jeju/hallasan_mountain.jpg" },
      { name: "우도", desc: "배를 타고 가는 작은 섬 여행", img: "images/spots/jeju/udo_island.jpg" },
      { name: "협재해수욕장", desc: "에메랄드빛 바다가 아름다운 해변", img: "images/spots/jeju/hyeopjae_beach.jpg" },
    ],
    enjoy: [
      { name: "해변 산책", desc: "협재, 함덕 등 해변에서 여유롭게 산책하기", img: "images/spots/jeju/beach.jpg" },
      { name: "드라이브", desc: "해안도로를 따라 드라이브하기", img: "images/spots/jeju/drive.jpg" },
      { name: "흑돼지 맛보기", desc: "제주 대표 음식을 현지에서 먹어보기", img: "images/spots/jeju/black_pork.jpg" },
      { name: "카페 투어", desc: "오션뷰 카페에서 쉬어가기", img: "images/spots/jeju/cafe.jpg" },
    ],
    tips: [
      { title: "날씨 확인", text: "바람이 강할 수 있어 겉옷을 챙기세요." },
      { title: "렌트카 예약", text: "성수기에는 미리 예약하는 것이 좋아요." },
      { title: "일출 일정", text: "성산일출봉은 일찍 출발하세요." },
      { title: "우도 배 시간", text: "우도 가는 배 시간표를 미리 확인하세요." },
    ],
  },
  paris: {
    tag: "예술과 건축의 도시",
    heroDesc: "예술, 건축, 거리 풍경까지 볼거리가 많은 유럽의 대표 도시입니다.",
    intro: "파리는 유명한 랜드마크뿐 아니라 골목 카페와 박물관, 공원까지 즐길 거리가 많습니다. 천천히 걸으며 도시 분위기를 느끼는 여행이 잘 어울립니다.",
    season: "4월 ~ 6월, 9월 ~ 10월",
    cost: "약 150만원~",
    days: "5박 7일",
    flight: "약 12시간",
    spots: [
      { name: "에펠탑", desc: "파리를 상징하는 대표 랜드마크", img: "images/spots/paris/eiffel_tower.jpg", best: true },
      { name: "루브르 박물관", desc: "세계적인 미술 작품을 감상할 수 있는 곳", img: "images/spots/paris/louvre_museum.jpg" },
      { name: "몽마르트 언덕", desc: "언덕 위 예술가 거리와 전망", img: "images/spots/paris/montmartre_hill.jpg" },
      { name: "샹젤리제", desc: "쇼핑과 거리 산책하기 좋은 대로", img: "images/spots/paris/elysian_fields.jpg" },
    ],
    enjoy: [
      { name: "카페에서 쉬기", desc: "테라스 카페에서 여유롭게 휴식하기", img: "images/spots/paris/cafe.jpg" },
      { name: "미술관 관람", desc: "오랑주리, 오르세 등 미술관 방문하기", img: "images/spots/paris/art_museum.jpg" },
      { name: "강변 산책", desc: "센 강변을 따라 산책하기", img: "images/spots/paris/river.jpg" },
      { name: "베이커리", desc: "크루아상과 마카롱 맛보기", img: "images/spots/paris/bakery.jpg" },
    ],
    tips: [
      { title: "이른 시간 방문", text: "유명 명소는 오전이 덜 붐벼요." },
      { title: "소매치기 주의", text: "관광지 주변은 가방을 앞으로 메세요." },
      { title: "박물관 예약", text: "루브르는 사전 예약을 추천해요." },
      { title: "편한 신발", text: "도보 이동이 많으니 편한 신발을 준비하세요." },
    ],
  },
  bangkok: {
    tag: "사원과 야시장의 도시",
    heroDesc: "화려한 사원과 활기찬 야시장, 다양한 길거리 음식을 즐길 수 있습니다.",
    intro: "방콕은 사원, 시장, 길거리 음식, 쇼핑까지 하루에 여러 경험을 할 수 있는 도시입니다. 낮에는 사원과 쇼핑, 저녁에는 야시장과 강변 산책을 추천합니다.",
    season: "11월 ~ 2월",
    cost: "약 70만원~",
    days: "3박 4일",
    flight: "약 5시간 30분",
    spots: [
      { name: "왓 아룬", desc: "차오프라야 강변의 상징적인 사원", img: "images/spots/bangkok/temple_of_dawn.jpg", best: true },
      { name: "차오프라야 강", desc: "강변 크루즈와 야경", img: "images/spots/bangkok/chao_phraya_river.jpg" },
      { name: "짜뚜짝 시장", desc: "주말에 열리는 대형 플리마켓", img: "images/spots/bangkok/chatuchak_market.jpg" },
      { name: "방콕 왕궁", desc: "태국 왕실의 역사적인 건축물", img: "images/spots/bangkok/bangkok_palace.jpg" },
    ],
    enjoy: [
      { name: "마사지", desc: "현지 마사지샵에서 휴식하기", img: "images/spots/bangkok/massage.jpg" },
      { name: "길거리 음식", desc: "팟타이와 망고 스티키 라이스 먹어보기", img: "images/spots/bangkok/food.jpg" },
      { name: "야시장", desc: "저녁 시장에서 쇼핑과 먹거리 즐기기", img: "images/spots/bangkok/market.jpg" },
      { name: "강 크루즈", desc: "저녁 강변 크루즈 타기", img: "images/spots/bangkok/cruise.jpg" },
    ],
    tips: [
      { title: "수분 보충", text: "더운 날씨에 지치지 않게 물을 자주 마시세요." },
      { title: "사원 복장", text: "어깨와 무릎을 가리는 옷을 입으세요." },
      { title: "택시 미터 확인", text: "택시는 미터기 사용 여부를 확인하세요." },
      { title: "현금 준비", text: "시장에서는 현금사용이 편해요." },
    ],
  },
  hawaii: {
    tag: "푸른 바다와 자연이 아름다운 도시",
    heroDesc: "푸른 바다와 여유로운 분위기를 즐길 수 있는 휴양지입니다. 휴식과 자연을 함께 느끼기 좋습니다.",
    intro: "하와이는 해변, 트레킹, 쇼핑, 현지 음식까지 다양하게 즐길 수 있는 휴양지입니다. 날씨가 대체로 따뜻해 해변과 실내 일정을 나눠 잡으면 편합니다.",
    season: "3월 ~ 9월",
    cost: "약 150만원~",
    days: "5박 7일",
    flight: "약 8시간 30분",
    spots: [
      { name: "와이키키 해변", desc: "하와이를 대표하는 해변", img: "images/spots/hawaii/waikiki_beach.jpg", best: true },
      { name: "다이아몬드 헤드", desc: "트레킹과 전망을 함께 즐기는 곳", img: "images/spots/hawaii/diamond_head.jpg" },
      { name: "하나우마 베이", desc: "스노클링으로 유명한 만", img: "images/spots/hawaii/hanauma_bay.jpg" },
      { name: "진주만", desc: "역사와 기념관을 둘러볼 수 있는 곳", img: "images/spots/hawaii/pearl_harbor.jpg" },
    ],
    enjoy: [
      { name: "해변에서 쉬기", desc: "와이키키에서 여유롭게 휴식하기", img: "images/spots/hawaii/beach.jpg" },
      { name: "트레킹", desc: "다이아몬드 헤드 등산해보기", img: "images/spots/hawaii/trekking.jpg" },
      { name: "현지 음식", desc: "포케와 로코모코 먹어보기", img: "images/spots/hawaii/food.jpg" },
      { name: "쇼핑", desc: "알라모아나 등 쇼핑몰 방문하기", img: "images/spots/hawaii/shopping.jpg" },
    ],
    tips: [
      { title: "아침에 해변 가기", text: "한낮보다 아침이 덜 덥고 한적해요." },
      { title: "렌트카 이용", text: "섬 이동에 차가 있으면 편해요." },
      { title: "자외선 차단", text: "선크림을 자주 바르세요." },
      { title: "일몰 시간 확인", text: "해변 일몰은 시간표를 확인하세요." },
    ],
  },
  rome: {
    tag: "역사가 살아 있는 도시",
    heroDesc: "오래된 건축물과 넓은 광장, 이탈리아 음식을 함께 즐길 수 있습니다.",
    intro: "로마는 콜로세움, 바티칸, 트레비 분수 등 세계적인 명소가 모여 있는 도시입니다. 유명한 곳은 줄이 길 수 있어 여유 있는 일정을 잡는 것을 추천드립니다.",
    season: "4월 ~ 6월, 9월 ~ 10월",
    cost: "약 140만원~",
    days: "4박 5일",
    flight: "약 12시간",
    spots: [
      { name: "콜로세움", desc: "로마를 대표하는 고대 원형 경기장", img: "images/spots/rome/colosseum.jpg", best: true },
      { name: "트레비 분수", desc: "동전을 던지는 전통이 있는 분수", img: "images/spots/rome/trevi_fountain.jpg" },
      { name: "바티칸 투어", desc: "성 베드로 대성당과 박물관", img: "images/spots/rome/st_peters_basilica.jpg" },
      { name: "스페인 광장", desc: "넓은 계단과 광장 산책", img: "images/spots/rome/spain_square.jpg" },
    ],
    enjoy: [
      { name: "파스타 맛보기", desc: "현지 트라토리아에서 식사 즐기기", img: "images/spots/rome/pasta.jpg" },
      { name: "광장 산책", desc: "나보나 광장과 주변 거리 산책하기", img: "images/spots/rome/walk.jpg" },
      { name: "젤라또", desc: "길거리 젤라또 가게 탐방하기", img: "images/spots/rome/ice_cream.jpg" },
      { name: "야경 보기", desc: "콜로세움 야경 감상하기", img: "images/spots/rome/night_view.jpg" },
    ],
    tips: [
      { title: "티켓 예약", text: "콜로세움은 사전 예약을 추천해요." },
      { title: "소매치기 주의", text: "관광지 주변은 소지품을 주의하세요." },
      { title: "줄 서기", text: "인기 명소는 웨이팅이 길 수 있어요." },
      { title: "편한 신발", text: "돌길이 많아 편한 신발이 필요해요." },
    ],
  },
  fukuoka: {
    tag: "가깝게 다녀오는 일본 서쪽의 도시",
    heroDesc: "라멘과 야타이 문화가 특히 유명한, 가깝게 다녀오기 좋은 도시입니다.",
    intro: "후쿠오카는 비행 시간이 짧고 도심과 해변이 가까워 주말 여행하기에 좋습니다. 낮에는 관광, 저녁에는 야타이에서 현지 음식을 즐기는 걸 추천드립니다.",
    season: "3월 ~ 5월, 10월",
    cost: "약 60만원~",
    days: "2박 3일",
    flight: "약 1시간",
    spots: [
      { name: "오호리 공원", desc: "도심 속 호수와 산책로", img: "images/spots/fukuoka/ohori_park.jpg", best: true },
      { name: "쿠시다 신사", desc: "후쿠오카의 대표 신사", img: "images/spots/fukuoka/kushida_shrine.jpg" },
      { name: "모모치 해변", desc: "도시와 바다를 함께 보는 해변", img: "images/spots/fukuoka/momochi_beach.jpg" },
      { name: "캐널시티", desc: "쇼핑과 공연을 즐길 수 있는 복합몰", img: "images/spots/fukuoka/canal_city.jpg" },
    ],
    enjoy: [
      { name: "야타이(포장마차)", desc: "저녁 포장마차에서 라멘과 꼬치 먹어보기", img: "images/spots/fukuoka/yatai.jpg" },
      { name: "해변 산책", desc: "모모치 해변에서 바다 보기", img: "images/spots/fukuoka/beach.jpg" },
      { name: "쇼핑", desc: "텐진과 하카타역 주변 쇼핑 즐기기", img: "images/spots/fukuoka/shopping.jpg" },
      { name: "온천", desc: "근교 온천에서 휴식하기", img: "images/spots/fukuoka/spa.jpg" },
    ],
    tips: [
      { title: "야타이는 저녁", text: "포장마차는 해 질 무렵부터 열려요." },
      { title: "현금 준비", text: "야타이는 현금만 받는 경우가 많아요." },
      { title: "짧은 일정 추천", text: "2~3일로도 충분히 즐길 수 있어요." },
      { title: "교통패스", text: "지하철 1일권이 있으면 편해요." },
    ],
  },
  busan: {
    tag: "바다와 도시를 함께 즐기는 도시",
    heroDesc: "해운대, 광안리 등 해변 산책이 인기 있는 국내 여행지입니다.",
    intro: "부산은 바다, 시장, 카페, 문화 마을까지 다양한 매력이 있는 도시입니다. KTX로 접근하기 쉬워 당일치기부터 2~3일 여행까지 모두 가능합니다.",
    season: "5월 ~ 6월, 9월 ~ 10월",
    cost: "약 40만원~",
    days: "2박 3일",
    flight: "KTX 약 2시간 30분",
    spots: [
      { name: "해운대 해수욕장", desc: "부산을 대표하는 해변", img: "images/spots/busan/haeundae_beach.jpg", best: true },
      { name: "감천 문화마을", desc: "알록달록한 언덕 마을", img: "images/spots/busan/gamcheon_culture_village.jpg" },
      { name: "자갈치 시장", desc: "신선한 해산물과 시장 구경", img: "images/spots/busan/jagalchi_market.jpg" },
      { name: "광안리 해수욕장", desc: "야경이 아름다운 해변", img: "images/spots/busan/gwangalli_beach.jpg" },
    ],
    enjoy: [
      { name: "해변 산책", desc: "해운대와 광안리 해변 걷기", img: "images/spots/busan/walk.jpg" },
      { name: "시장 구경", desc: "자갈치와 국제시장 둘러보기", img: "images/spots/busan/market.jpg" },
      { name: "회 맛보기", desc: "현지 회와 해물 요리 먹어보기", img: "images/spots/busan/sashimi.jpg" },
      { name: "야경 보기", desc: "광안대교 야경 감상하기", img: "images/spots/busan/night_view.jpg" },
    ],
    tips: [
      { title: "해변 + 시장", text: "해변과 시장을 같은 날 넣으면 동선이 좋아요." },
      { title: "KTX 예매", text: "주말에는 미리 예매하세요." },
      { title: "감천 마을", text: "언덕길이라 편한 신발이 좋아요." },
      { title: "광안리 야경", text: "저녁에 광안리를 방문해 보세요." },
    ],
  },
  london: {
    tag: "박물관과 공원의 도시",
    heroDesc: "박물관, 공원, 클래식한 거리 풍경을 즐길 수 있는 영국의 대표 도시입니다.",
    intro: "런던은 대영박물관, 하이드 파크, 빅벤 등 다양한 볼거리가 있는 도시입니다. 박물관은 무료인 곳이 많아 천천히 둘러보기 좋습니다.",
    season: "5월 ~ 9월",
    cost: "약 160만원~",
    days: "5박 7일",
    flight: "약 12시간",
    spots: [
      { name: "빅벤", desc: "런던을 상징하는 시계탑", img: "images/spots/london/big_ben.jpg", best: true },
      { name: "대영박물관", desc: "무료로 관람할 수 있는 대형 박물관", img: "images/spots/london/british_museum.jpg" },
      { name: "하이드 파크", desc: "넓은 공원에서 산책과 휴식", img: "images/spots/london/hyde_park.jpg" },
      { name: "런던 아이", desc: "템즈강변 전망을 볼 수 있는 관람차", img: "images/spots/london/london_eye.jpg" },
    ],
    enjoy: [
      { name: "박물관 관람", desc: "대영박물관과 내셔널 갤러리 방문하기", img: "images/spots/london/museum.jpg" },
      { name: "공원 산책", desc: "하이드 파크와 세인트제임스 공원 산책하기", img: "images/spots/london/park.jpg" },
      { name: "브런치", desc: "현지 카페에서 브런치 즐기기", img: "images/spots/london/brunch.jpg" },
      { name: "강변 산책", desc: "템즈강변을 따라 산책하기", img: "images/spots/london/riverside.jpg" },
    ],
    tips: [
      { title: "Oyster 카드", text: "대중교통 카드를 준비하면 편해요." },
      { title: "박물관 무료", text: "대형 박물관은 무료 입장이 많아요." },
      { title: "날씨 대비", text: "비가 올 수 있어 우산을 챙기세요." },
      { title: "줄 서기", text: "인기 전시는 예약이 필요할 수 있어요." },
    ],
  },
  danang: {
    tag: "해변과 드라이브를 즐길 수 있는 베트남 도시",
    heroDesc: "해변 휴양과 가까운 드라이브 여행을 함께 즐기기 좋은 베트남 도시입니다.",
    intro: "다낭은 미케 비치와 바나힐, 호이안 등 근교 여행지가 가까운 도시입니다. 해변에서 쉬다가 하루는 근교 관광을 넣으면 좋습니다.",
    season: "2월 ~ 5월",
    cost: "약 60만원~",
    days: "3박 4일",
    flight: "약 4시간 30분",
    spots: [
      { name: "미케 비치", desc: "다낭을 대표하는 해변", img: "images/spots/danang/my_khe_beach.jpg", best: true },
      { name: "용다리", desc: "주말 밤 불꽃쇼가 있는 다리", img: "images/spots/danang/dragon_bridge.jpg" },
      { name: "바나힐", desc: "케이블카와 테마파크", img: "images/spots/danang/bana_hills.jpg" },
      { name: "호이안", desc: "근교 올드타운과 등불 거리", img: "images/spots/danang/hoi_an.jpg" },
    ],
    enjoy: [
      { name: "해변 휴양", desc: "미케 비치에서 수영과 휴식 즐기기", img: "images/spots/danang/beach.jpg" },
      { name: "참 박물관", desc: "다양한 유물과 건축 양식 구경하기", img: "images/spots/danang/cham_sculpture_museum.jpg" },
      { name: "골든 브릿지", desc: "손 모양 조형물과 함께 자연을 감상하기", img: "images/spots/danang/golden_bridge.jpg" },
      { name: "베트남 음식", desc: "쌀국수와 반미 먹어보기", img: "images/spots/danang/noodle.jpg" },
    ],
    tips: [
      { title: "호이안 일정", text: "호이안은 하루 일정으로 넣기 좋아요." },
      { title: "용다리 불꽃", text: "주말 밤 불꽃 시간을 확인하세요." },
      { title: "렌트카/투어", text: "바나힐은 투어 또는 렌트가 편해요." },
      { title: "자외선 차단", text: "해변에서는 선크림을 꼭 바르세요." },
    ],
  },
  taipei: {
    tag: "야시장과 카페가 아름다운 도시",
    heroDesc: "야시장, 전통 거리, 카페와 쇼핑을 함께 즐길 수 있는 가까운 해외 여행지입니다.",
    intro: "타이베이는 101, 지우펀, 용산사 등 볼거리와 먹거리가 가까운 도시입니다. 비행 시간이 짧아 첫 해외 여행지로도 많이 선택됩니다.",
    season: "3월 ~ 5월, 10월 ~ 11월",
    cost: "약 70만원~",
    days: "3박 4일",
    flight: "약 2시간 30분",
    spots: [
      { name: "타이베이 101", desc: "타이베이를 대표하는 마천루", img: "images/spots/taipei/taipei_101.jpg", best: true },
      { name: "지우펀", desc: "등불과 골목길이 아름다운 올드타운", img: "images/spots/taipei/jiufen.jpg" },
      { name: "용산사", desc: "타이베이 최초의 불교 사찰", img: "images/spots/taipei/longshan_temple.jpg" },
      { name: "스린 야시장", desc: "먹거리와 쇼핑이 있는 야시장", img: "images/spots/taipei/shilin_night_market.jpg" },
    ],
    enjoy: [
      { name: "야시장", desc: "스린, 닝샤 등 야시장 탐방하기", img: "images/spots/taipei/market.jpg" },
      { name: "카페", desc: "현지 카페거리에서 브런치 즐기기", img: "images/spots/taipei/cafe.jpg" },
      { name: "동물원", desc: "시립 동물원에서 다양한 동물 관람하기", img: "images/spots/taipei/zoo.jpg" },
      { name: "쇼핑", desc: "101과 시먼딩에서 쇼핑 즐기기", img: "images/spots/taipei/shopping.jpg" },
    ],
    tips: [
      { title: "야시장은 저녁", text: "야시장은 해 질 무렵부터 즐길 수 있어요." },
      { title: "지우펀 버스", text: "지우펀은 버스 시간표를 확인하세요." },
      { title: "EasyCard", text: "교통카드를 준비하면 편해요." },
      { title: "우산 준비", text: "갑자기 비가 올 수 있어요." },
    ],
  },
  sydney: {
    tag: "항구와 해변의 도시",
    heroDesc: "오페라하우스와 항구 풍경이 아름다운 호주의 대표 도시입니다.",
    intro: "시드니는 오페라하우스, 하버 브리지, 본다이 비치 등 자연과 도시를 함께 즐길 수 있습니다. 항구 주변은 낮과 밤 분위기가 달라 산책하기 좋습니다.",
    season: "10월 ~ 4월",
    cost: "약 180만원~",
    days: "5박 7일",
    flight: "약 10시간",
    spots: [
      { name: "오페라하우스", desc: "시드니를 상징하는 건축물", img: "images/spots/sydney/opera_house.jpg", best: true },
      { name: "하버 브리지", desc: "항구를 가로지르는 대표 다리", img: "images/spots/sydney/harbor_bridge.jpg" },
      { name: "포트스테판", desc: "모래 사막에서 즐기는 모래 썰매", img: "images/spots/sydney/port_stephens.jpg" },
      { name: "본다이 비치", desc: "서핑과 해변 휴양", img: "images/spots/sydney/bondi_beach.jpg" },
    ],
    enjoy: [
      { name: "해변", desc: "본다이와 맨리 비치 방문해보기", img: "images/spots/sydney/beach.jpg" },
      { name: "항구 산책", desc: "서큘러 키를 따라 산책하기", img: "images/spots/sydney/walk.jpg" },
      { name: "브런치", desc: "항구변 카페에서 식사 즐기기", img: "images/spots/sydney/brunch.jpg" },
      { name: "야경", desc: "오페라하우스 야경 감상하기", img: "images/spots/sydney/night_view.jpg" },
    ],
    tips: [
      { title: "Opal 카드", text: "대중교통 카드를 준비하세요." },
      { title: "자외선", text: "햇볕이 강해 선크림이 필요해요." },
      { title: "항구 산책", text: "저녁에 서큘러 키의 풍경이 특히 예뻐요." },
      { title: "페리 이용", text: "항구 페리로 이동하면 경치가 좋아요." },
    ],
  },
  newyork: {
    tag: "현대적인 볼거리가 가득한 세계적인 도시",
    heroDesc: "뮤지컬, 박물관, 거리 풍경까지 볼거리가 많은 세계적인 도시입니다.",
    intro: "뉴욕은 타임스퀘어, 센트럴 파크, 자유의 여신상 등 유명한 장소가 많습니다. 동선을 구역별로 나눠서 보고 다니는 걸 추천드립니다.",
    season: "4월 ~ 6월, 9월 ~ 11월",
    cost: "약 200만원~",
    days: "5박 7일",
    flight: "약 14시간",
    spots: [
      { name: "타임스퀘어", desc: "뉴욕의 상징적인 번화가", img: "images/spots/newyork/times_square.jpg", best: true },
      { name: "센트럴 파크", desc: "도심 속 넓은 공원", img: "images/spots/newyork/central_park.jpg" },
      { name: "자유의 여신상", desc: "뉴욕을 대표하는 상징", img: "images/spots/newyork/statue_of_liberty.jpg" },
      { name: "브루클린 브리지", desc: "브루클린 다리와 전망", img: "images/spots/newyork/brooklyn_bridge.jpg" },
    ],
    enjoy: [
      { name: "뮤지컬", desc: "브로드웨이 공연 관람하기", img: "images/spots/newyork/musical.jpg" },
      { name: "공원 산책", desc: "센트럴 파크에서 휴식하기", img: "images/spots/newyork/walk.jpg" },
      { name: "미술관", desc: "Met, MoMA 등의 미술관 관람하기", img: "images/spots/newyork/art_museum.jpg" },
      { name: "거리 구경", desc: "SOHO, 첼시 마켓 탐방하기", img: "images/spots/newyork/market.jpg" },
    ],
    tips: [
      { title: "구역별 동선", text: "도시가 넓으니 하루에 한 구역씩 나눠 보세요." },
      { title: "팁 문화", text: "식당과 택시에 팁이 필요해요." },
      { title: "MetroCard", text: "지하철 이용권을 준비하세요." },
      { title: "편한 신발", text: "걸어 다니는 시간이 많아요." },
    ],
  },
};
